#include <iostream>
#include <vector>
#include <functional>

void test_gps_parses_gga_fix();
void test_gps_parses_rmc_course_and_speed();
void test_gps_validates_good_and_bad_checksums();
void test_gps_rejects_missing_and_malformed_checksums();
void test_gps_parser_detailed_rejects_invalid_checksum();
void test_gps_parser_accepts_lowercase_checksum_and_crlf();
void test_gps_stream_buffers_fragmented_and_multiple_lines();
void test_gps_stream_discards_garbage_before_sentence();
void test_gps_serial_receiver_reads_fragmented_fix_from_pty();
void test_gps_serial_receiver_skips_bad_checksum_then_returns_good_fix();
void test_gps_serial_receiver_timeout_reports_status();
void test_gps_serial_receiver_rejects_invalid_config();
void test_network_gps_parser_accepts_plain_json_and_nmea_payloads();
void test_network_gps_parser_rejects_malformed_json_payloads();
void test_network_gps_udp_receiver_reads_single_packet_fix();
void test_network_gps_tcp_receiver_handles_fragmented_newline_feed();
void test_network_gps_receiver_reports_timeout_and_invalid_config();
void test_network_gps_tcp_open_uses_configured_finite_timeout();
void test_network_gps_tcp_read_has_overall_deadline_without_newline();
void test_network_gps_tcp_read_uses_remaining_deadline_after_partial_payload();
void test_odometry_differential_drive_forward_and_turn();
void test_coordinate_local_conversion();
void test_obstacle_sector_calculation();
void test_depth_frame_extracts_nearest_obstacle_sectors();
void test_depth_frame_to_point_cloud_projects_valid_pixels();
void test_depth_frame_ignores_invalid_pixels_and_bad_fixtures();
void test_motor_command_validation_and_estop();
void test_config_loader_reads_key_values();
void test_serial_port_open_timeout_write_read_and_close();
void test_serial_port_rejects_invalid_configuration();
void test_motor_calibration_save_load_round_trip();
void test_motor_calibration_load_rejects_invalid_values();
void test_motor_calibration_load_missing_file_returns_error();
void test_maps_nearest_path_index_selects_closest_path();
void test_maps_nearest_path_index_empty_map_returns_invalid_index();
void test_maps_csv_loader_loads_fixture_route_and_sorts_by_sequence();
void test_maps_csv_loader_loads_multiple_paths();
void test_maps_csv_loader_reports_missing_file();
void test_maps_csv_loader_reports_invalid_row();
void test_maps_csv_loader_reports_empty_route();
void test_maps_buchlovice_graph_loader_builds_bidirectional_edges();
void test_maps_buchlovice_graph_loader_reports_invalid_rows();
void test_maps_graph_nearest_vertex_and_shortest_path();
void test_maps_graph_sample_route_adds_spacing_points();
void test_maps_route_reuse_decision_uses_distance_from_current_route();
void test_maps_geo_helpers_compute_distance_bearing_and_signed_angle();
void test_maps_bearing_to_ahead_point_follows_straight_route();
void test_maps_turn_ahead_detects_left_and_right_turns();
void test_maps_turn_ahead_handles_duplicate_leading_route_points();
void test_maps_turn_ahead_uses_next_measurable_segment_after_duplicate_vertex();
void test_maps_route_cues_reject_non_finite_coordinates();
void test_maps_turn_ahead_returns_none_for_straight_and_empty_routes();
void test_maps_wrong_direction_detector_uses_persistence_and_distance_growth();
void test_maps_wrong_direction_detector_ignores_stationary_and_noisy_gps();
void test_navigation_go_to_waypoint_stops_inside_tolerance();
void test_navigation_route_follower_advances_waypoints();
void test_navigation_route_follower_finishes_route();
void test_navigation_route_follower_empty_route_reports_finished();
void test_navigation_route_follower_obstacle_does_not_advance_unless_reached();
void test_runtime_countdown_start_and_arrival_flow_is_deterministic();
void test_runtime_faults_on_unhealthy_critical_module();
void test_runtime_obstacle_wait_bypass_and_resume_flow();
void test_runtime_motor_keepalive_due_uses_deterministic_ticks();
void test_mission_target_parser_accepts_geo_and_gps_formats();
void test_mission_target_parser_accepts_labeled_and_hemisphere_formats();
void test_mission_target_parser_rejects_invalid_payloads_with_status();
void test_qr_mission_source_uses_decoder_backend_when_enabled();
void test_runtime_allows_optional_camera_depth_degraded_mode();
void test_runtime_faults_on_stale_module_freshness();
void test_imu_tilt_detects_lateral_acceleration_threshold();
void test_imu_collision_detects_total_acceleration_spike();
void test_imu_pose_fusion_normalizes_heading_and_blends_gps_correction();
void test_imu_pose_fusion_rejects_invalid_weights();
void test_imu_pose_fusion_ignores_gps_without_origin_or_fix();
void test_imu_pose_fusion_weight_boundaries_select_sources();
void test_imu_pose_fusion_replays_fixture_samples();
void test_camera_expected_byte_size_and_shape_for_rgb_frame();
void test_camera_validates_fake_camera_frame_metadata_and_payload();
void test_camera_rejects_invalid_metadata_and_payload_size();
void test_perception_detects_centered_left_and_right_paths();
void test_perception_grass_and_dark_side_coverage_helpers();
void test_perception_low_confidence_invalid_config_and_invalid_frames_fail_safe();
void test_perception_side_coverage_handles_narrow_frames();
void test_telemetry_parser_loads_robotour_fixture();
void test_telemetry_parser_rejects_bad_schema_and_rows();
void test_telemetry_replay_produces_deterministic_navigation_decisions();
void test_telemetry_replay_builds_deterministic_ui_snapshot_sequence();
void test_ui_map_view_projects_markers_into_viewport();
void test_ui_map_view_preserves_metric_aspect_ratio_in_wide_viewport();
void test_ui_map_view_marks_off_axis_point_in_degenerate_bounds_invisible();
void test_ui_mission_overlay_classifies_start_operation_current_and_final_positions();
void test_ui_snapshot_composer_connects_map_camera_kinect_and_robot_state();
void test_ui_snapshot_composer_reports_invalid_stream_payloads();
void test_ui_snapshot_composer_reports_invalid_kinect_depth_payloads();
void test_ui_viewport_validation_rejects_excessive_padding_without_overflow();
void test_ui_text_dashboard_renders_mission_stream_and_marker_summary();
void test_ui_renderer_interface_receives_snapshots_at_mission_rate();
void test_ui_renderer_interface_propagates_render_failures_to_event_sink();
#ifdef ROZETA_WITH_SERIAL_MOTORS
void test_serial_motor_formats_normalized_speed_commands();
void test_serial_motor_rejects_invalid_speed_without_writing();
void test_serial_motor_stop_writes_configured_stop_command();
void test_serial_motor_emergency_stop_writes_stop_then_refuses_motion();
void test_serial_motor_clear_emergency_stop_allows_motion();
void test_serial_motor_emergency_stop_writes_stop_even_when_motion_config_is_invalid();
void test_serial_motor_rejects_command_prefix_with_control_characters();
void test_serial_motor_propagates_transport_write_errors();
void test_serial_motor_formats_buchlovice_binary_packets();
void test_serial_motor_buchlovice_stop_and_spin_packets();
void test_serial_motor_buchlovice_emergency_stop_bypasses_invalid_motion_config();
#endif
#ifdef ROZETA_WITH_YDLIDAR
void test_ydlidar_parser_parses_sample_frame();
void test_ydlidar_parser_accepts_fragmented_frame();
void test_ydlidar_parser_discards_garbage_before_frame();
void test_ydlidar_parser_rejects_invalid_packets_without_throwing();
void test_ydlidar_parser_normalizes_wraparound_angles();
void test_ydlidar_backend_invalid_device_reports_hardware_unavailable();
#endif

int main(){
    std::vector<std::pair<const char*, std::function<void()>>> tests = {
        {"gps_gga", test_gps_parses_gga_fix},
        {"gps_rmc", test_gps_parses_rmc_course_and_speed},
        {"gps_checksum", test_gps_validates_good_and_bad_checksums},
        {"gps_checksum_malformed", test_gps_rejects_missing_and_malformed_checksums},
        {"gps_detailed_bad_checksum", test_gps_parser_detailed_rejects_invalid_checksum},
        {"gps_detailed_crlf", test_gps_parser_accepts_lowercase_checksum_and_crlf},
        {"gps_stream_fragmented", test_gps_stream_buffers_fragmented_and_multiple_lines},
        {"gps_stream_garbage", test_gps_stream_discards_garbage_before_sentence},
        {"gps_serial_fragmented", test_gps_serial_receiver_reads_fragmented_fix_from_pty},
        {"gps_serial_skip_bad", test_gps_serial_receiver_skips_bad_checksum_then_returns_good_fix},
        {"gps_serial_timeout", test_gps_serial_receiver_timeout_reports_status},
        {"gps_serial_invalid_config", test_gps_serial_receiver_rejects_invalid_config},
        {"network_gps_payload_parse", test_network_gps_parser_accepts_plain_json_and_nmea_payloads},
        {"network_gps_json_rejects_malformed", test_network_gps_parser_rejects_malformed_json_payloads},
        {"network_gps_udp_packet", test_network_gps_udp_receiver_reads_single_packet_fix},
        {"network_gps_tcp_fragmented", test_network_gps_tcp_receiver_handles_fragmented_newline_feed},
        {"network_gps_timeout_config", test_network_gps_receiver_reports_timeout_and_invalid_config},
        {"network_gps_tcp_open_timeout", test_network_gps_tcp_open_uses_configured_finite_timeout},
        {"network_gps_tcp_read_deadline", test_network_gps_tcp_read_has_overall_deadline_without_newline},
        {"network_gps_tcp_partial_deadline", test_network_gps_tcp_read_uses_remaining_deadline_after_partial_payload},
        {"odometry", test_odometry_differential_drive_forward_and_turn},
        {"coordinates", test_coordinate_local_conversion},
        {"obstacles", test_obstacle_sector_calculation},
        {"depth_obstacles", test_depth_frame_extracts_nearest_obstacle_sectors},
        {"depth_point_cloud", test_depth_frame_to_point_cloud_projects_valid_pixels},
        {"depth_edge_cases", test_depth_frame_ignores_invalid_pixels_and_bad_fixtures},
        {"motors", test_motor_command_validation_and_estop},
        {"config", test_config_loader_reads_key_values},
        {"serial_port", test_serial_port_open_timeout_write_read_and_close},
        {"serial_invalid_config", test_serial_port_rejects_invalid_configuration},
        {"motor_calibration_round_trip", test_motor_calibration_save_load_round_trip},
        {"motor_calibration_invalid", test_motor_calibration_load_rejects_invalid_values},
        {"motor_calibration_missing", test_motor_calibration_load_missing_file_returns_error},
        {"maps_nearest_path", test_maps_nearest_path_index_selects_closest_path},
        {"maps_empty_index", test_maps_nearest_path_index_empty_map_returns_invalid_index},
        {"maps_csv_fixture", test_maps_csv_loader_loads_fixture_route_and_sorts_by_sequence},
        {"maps_csv_multiple_paths", test_maps_csv_loader_loads_multiple_paths},
        {"maps_missing_file", test_maps_csv_loader_reports_missing_file},
        {"maps_invalid_row", test_maps_csv_loader_reports_invalid_row},
        {"maps_empty_route", test_maps_csv_loader_reports_empty_route},
        {"maps_buchlovice_graph", test_maps_buchlovice_graph_loader_builds_bidirectional_edges},
        {"maps_buchlovice_graph_invalid", test_maps_buchlovice_graph_loader_reports_invalid_rows},
        {"maps_graph_shortest_path", test_maps_graph_nearest_vertex_and_shortest_path},
        {"maps_graph_sample_route", test_maps_graph_sample_route_adds_spacing_points},
        {"maps_graph_route_reuse", test_maps_route_reuse_decision_uses_distance_from_current_route},
        {"maps_geo_helpers", test_maps_geo_helpers_compute_distance_bearing_and_signed_angle},
        {"maps_bearing_ahead", test_maps_bearing_to_ahead_point_follows_straight_route},
        {"maps_turn_ahead", test_maps_turn_ahead_detects_left_and_right_turns},
        {"maps_turn_duplicate_points", test_maps_turn_ahead_handles_duplicate_leading_route_points},
        {"maps_turn_duplicate_vertex", test_maps_turn_ahead_uses_next_measurable_segment_after_duplicate_vertex},
        {"maps_route_cue_invalid", test_maps_route_cues_reject_non_finite_coordinates},
        {"maps_turn_ahead_none", test_maps_turn_ahead_returns_none_for_straight_and_empty_routes},
        {"maps_wrong_direction", test_maps_wrong_direction_detector_uses_persistence_and_distance_growth},
        {"maps_wrong_direction_noise", test_maps_wrong_direction_detector_ignores_stationary_and_noisy_gps},
        {"navigation_waypoint_tolerance", test_navigation_go_to_waypoint_stops_inside_tolerance},
        {"navigation_route_advance", test_navigation_route_follower_advances_waypoints},
        {"navigation_route_complete", test_navigation_route_follower_finishes_route},
        {"navigation_route_empty", test_navigation_route_follower_empty_route_reports_finished},
        {"navigation_route_obstacle", test_navigation_route_follower_obstacle_does_not_advance_unless_reached},
        {"runtime_countdown_arrival", test_runtime_countdown_start_and_arrival_flow_is_deterministic},
        {"runtime_fault_unhealthy_module", test_runtime_faults_on_unhealthy_critical_module},
        {"runtime_obstacle_bypass", test_runtime_obstacle_wait_bypass_and_resume_flow},
        {"runtime_motor_keepalive", test_runtime_motor_keepalive_due_uses_deterministic_ticks},
        {"mission_geo_gps_parse", test_mission_target_parser_accepts_geo_and_gps_formats},
        {"mission_labeled_hemisphere_parse", test_mission_target_parser_accepts_labeled_and_hemisphere_formats},
        {"mission_rejects_invalid_payloads", test_mission_target_parser_rejects_invalid_payloads_with_status},
        {"mission_qr_backend", test_qr_mission_source_uses_decoder_backend_when_enabled},
        {"runtime_optional_degraded", test_runtime_allows_optional_camera_depth_degraded_mode},
        {"runtime_stale_module", test_runtime_faults_on_stale_module_freshness},
        {"imu_tilt", test_imu_tilt_detects_lateral_acceleration_threshold},
        {"imu_collision", test_imu_collision_detects_total_acceleration_spike},
        {"imu_pose_fusion", test_imu_pose_fusion_normalizes_heading_and_blends_gps_correction},
        {"imu_invalid_weights", test_imu_pose_fusion_rejects_invalid_weights},
        {"imu_gps_edge_cases", test_imu_pose_fusion_ignores_gps_without_origin_or_fix},
        {"imu_weight_boundaries", test_imu_pose_fusion_weight_boundaries_select_sources},
        {"imu_fixture_replay", test_imu_pose_fusion_replays_fixture_samples},
        {"camera_shape", test_camera_expected_byte_size_and_shape_for_rgb_frame},
        {"camera_fake_frame", test_camera_validates_fake_camera_frame_metadata_and_payload},
        {"camera_invalid_frame", test_camera_rejects_invalid_metadata_and_payload_size},
        {"perception_path", test_perception_detects_centered_left_and_right_paths},
        {"perception_coverage", test_perception_grass_and_dark_side_coverage_helpers},
        {"perception_invalid", test_perception_low_confidence_invalid_config_and_invalid_frames_fail_safe},
        {"perception_narrow", test_perception_side_coverage_handles_narrow_frames},
        {"telemetry_parser_fixture", test_telemetry_parser_loads_robotour_fixture},
        {"telemetry_parser_errors", test_telemetry_parser_rejects_bad_schema_and_rows},
        {"telemetry_replay_deterministic", test_telemetry_replay_produces_deterministic_navigation_decisions},
        {"telemetry_ui_snapshots", test_telemetry_replay_builds_deterministic_ui_snapshot_sequence},
        {"ui_map_projection", test_ui_map_view_projects_markers_into_viewport},
        {"ui_metric_aspect", test_ui_map_view_preserves_metric_aspect_ratio_in_wide_viewport},
        {"ui_degenerate_bounds", test_ui_map_view_marks_off_axis_point_in_degenerate_bounds_invisible},
        {"ui_mission_overlay", test_ui_mission_overlay_classifies_start_operation_current_and_final_positions},
        {"ui_snapshot_composer", test_ui_snapshot_composer_connects_map_camera_kinect_and_robot_state},
        {"ui_invalid_stream", test_ui_snapshot_composer_reports_invalid_stream_payloads},
        {"ui_invalid_depth", test_ui_snapshot_composer_reports_invalid_kinect_depth_payloads},
        {"ui_invalid_viewport", test_ui_viewport_validation_rejects_excessive_padding_without_overflow},
        {"ui_text_dashboard", test_ui_text_dashboard_renders_mission_stream_and_marker_summary},
        {"ui_renderer_frames", test_ui_renderer_interface_receives_snapshots_at_mission_rate},
        {"ui_renderer_status", test_ui_renderer_interface_propagates_render_failures_to_event_sink},
#ifdef ROZETA_WITH_SERIAL_MOTORS
        {"serial_motor_format", test_serial_motor_formats_normalized_speed_commands},
        {"serial_motor_invalid_speed", test_serial_motor_rejects_invalid_speed_without_writing},
        {"serial_motor_stop", test_serial_motor_stop_writes_configured_stop_command},
        {"serial_motor_estop", test_serial_motor_emergency_stop_writes_stop_then_refuses_motion},
        {"serial_motor_clear_estop", test_serial_motor_clear_emergency_stop_allows_motion},
        {"serial_motor_estop_ignores_motion_config", test_serial_motor_emergency_stop_writes_stop_even_when_motion_config_is_invalid},
        {"serial_motor_prefix_validation", test_serial_motor_rejects_command_prefix_with_control_characters},
        {"serial_motor_write_error", test_serial_motor_propagates_transport_write_errors},
        {"serial_motor_buchlovice_packet", test_serial_motor_formats_buchlovice_binary_packets},
        {"serial_motor_buchlovice_stop_spin", test_serial_motor_buchlovice_stop_and_spin_packets},
        {"serial_motor_buchlovice_estop", test_serial_motor_buchlovice_emergency_stop_bypasses_invalid_motion_config},
#endif
#ifdef ROZETA_WITH_YDLIDAR
        {"ydlidar_parse_fixture", test_ydlidar_parser_parses_sample_frame},
        {"ydlidar_fragmented", test_ydlidar_parser_accepts_fragmented_frame},
        {"ydlidar_garbage", test_ydlidar_parser_discards_garbage_before_frame},
        {"ydlidar_invalid_safe", test_ydlidar_parser_rejects_invalid_packets_without_throwing},
        {"ydlidar_wraparound", test_ydlidar_parser_normalizes_wraparound_angles},
        {"ydlidar_invalid_device", test_ydlidar_backend_invalid_device_reports_hardware_unavailable},
#endif
    };
    int failed = 0;
    for (auto &test : tests) {
        try { test.second(); std::cout << "[PASS] " << test.first << "\n"; }
        catch (const std::exception &e) { ++failed; std::cerr << "[FAIL] " << test.first << ": " << e.what() << "\n"; }
    }
    return failed == 0 ? 0 : 1;
}
