#include <iostream>
#include <vector>
#include <functional>

void test_gps_parses_gga_fix();
void test_gps_parses_rmc_course_and_speed();
void test_gps_validates_good_and_bad_checksums();
void test_gps_rejects_missing_and_malformed_checksums();
void test_gps_parser_detailed_rejects_invalid_checksum();
void test_gps_parser_accepts_lowercase_checksum_and_crlf();
void test_gps_stream_buffers_fragmented_and_multiple_lines();
void test_gps_stream_discards_garbage_before_sentence();
#if !defined(_WIN32)
void test_gps_serial_receiver_reads_fragmented_fix_from_pty();
void test_gps_serial_receiver_skips_bad_checksum_then_returns_good_fix();
void test_gps_serial_receiver_timeout_reports_status();
#endif
void test_gps_serial_receiver_rejects_invalid_config();
void test_gps_nmea_carries_the_sentence_time();
void test_gps_nmea_time_handles_fractions_and_absence();
void test_gps_network_receiver_rejects_invalid_config();
void test_network_gps_parser_accepts_plain_json_and_nmea_payloads();
void test_network_gps_parser_rejects_malformed_json_payloads();
void test_network_gps_udp_receiver_reads_single_packet_fix();
void test_network_gps_tcp_receiver_handles_fragmented_newline_feed();
void test_network_gps_receiver_reports_timeout_and_invalid_config();
void test_network_gps_tcp_open_uses_configured_finite_timeout();
void test_network_gps_tcp_read_has_overall_deadline_without_newline();
void test_network_gps_tcp_read_uses_remaining_deadline_after_partial_payload();
void test_odometry_differential_drive_forward_and_turn();
void test_odometry_heading_counterclockwise_positive();
void test_odometry_seed_ticks_prevents_startup_jump();
void test_coordinate_local_conversion();
void test_obstacle_sector_calculation();
void test_depth_frame_extracts_nearest_obstacle_sectors();
void test_depth_frame_to_point_cloud_projects_valid_pixels();
void test_depth_frame_ignores_invalid_pixels_and_bad_fixtures();
void test_motor_command_validation_and_estop();
void test_motor_rejects_non_finite_speeds();
void test_speed_ramp_accelerates_linearly_to_target();
void test_speed_ramp_decelerates_to_zero_and_stops();
void test_speed_ramp_rejects_invalid_configuration();
void test_smooth_drive_accelerates_and_brakes_within_profile();
void test_smooth_drive_repeats_command_for_bridge_watchdog();
void test_smooth_drive_reverses_through_standstill_and_validates();
void test_smooth_drive_emergency_stop_bypasses_ramp();
void test_config_loader_reads_key_values();
void test_config_load_file_reports_missing_and_loads_existing();
void test_normalize_angle_wraps_small_and_huge_magnitudes();
void test_logging_global_logger_swap_and_null_safe();
void test_logging_csv_file_logger_escapes_quotes_commas_newlines();
void test_logging_csv_file_logger_reports_unopenable_path();
void test_serial_port_open_timeout_write_read_and_close();
void test_serial_port_rejects_invalid_configuration();
void test_motor_calibration_save_load_round_trip();
void test_motor_calibration_load_rejects_invalid_values();
void test_motor_calibration_load_missing_file_returns_error();
void test_calibration_save_load_round_trip_for_field_tools();
void test_calibration_rejects_non_finite_and_out_of_range_values();
void test_calibration_load_fails_closed_for_bad_files();
void test_calibration_load_requires_complete_unique_snapshot_keys();
void test_calibration_rejects_revision_values_that_break_key_value_files();
void test_calibration_checklist_reports_camera_motor_gps_and_threshold_steps();
void test_hardware_smoke_matrix_builds_lifted_wheel_and_sensor_checks();
void test_hardware_smoke_matrix_fails_closed_without_estop_or_wheel_lift();
void test_hardware_smoke_matrix_renders_deterministic_operator_plan();
void test_hardware_smoke_matrix_validates_only_enabled_source_groups();
void test_hardware_smoke_matrix_rejects_invalid_calibration_and_quotes_commands();
void test_geometry_projects_point_on_segment();
void test_geometry_degenerate_segment_projects_to_start();
void test_geometry_polyline_distance_and_length();
void test_geometry_point_in_polygon();
void test_geometry_bounds();
void test_geometry_ray_hits_and_misses_segment();
void test_geometry_cast_ray_returns_closest_hit();
void test_geometry_ray_circle_intersection();
void test_geometry_rejects_non_finite_input();
void test_geodesy_haversine_matches_known_distances();
void test_geodesy_local_round_trip();
void test_geodesy_bearing_and_heading_conversions();
void test_geodesy_validates_coordinates();
void test_geodesy_resamples_polyline_with_exact_endpoints();
void test_geodesy_bounds_and_interpolation();
void test_geodesy_meters_per_degree_shrinks_towards_poles();
void test_kinematics_validates_chassis_config();
void test_kinematics_tank_mix_counter_rotates_through_turns();
void test_kinematics_arcade_mix_arcs_and_respects_limit();
void test_kinematics_mix_clamps_invalid_input();
void test_kinematics_wheel_speeds_and_twist_round_trip();
void test_kinematics_integrates_straight_turn_and_spin();
void test_kinematics_turning_in_place_detection_and_motor_commands();
void test_map_graph_snaps_onto_segment_not_only_vertices();
void test_map_graph_snap_rejects_far_and_invalid_points();
void test_map_graph_index_matches_brute_force_snap();
void test_map_graph_index_rejects_far_away_points_quickly();
void test_map_graph_validate_reports_components_and_length();
void test_map_graph_astar_matches_dijkstra();
void test_map_graph_astar_rejects_invalid_and_unreachable_vertices();
void test_map_graph_plan_route_snaps_both_endpoints();
void test_map_graph_plan_route_on_one_edge_stays_on_it();
void test_map_graph_plan_route_reports_unreachable_and_invalid_input();
void test_map_graph_loads_shipped_openstreetmap_dataset();
void test_map_catalog_loads_shipped_catalog();
void test_map_catalog_reports_bad_input();
void test_simulation_noise_is_deterministic_for_a_seed();
void test_simulation_world_validates_config();
void test_simulated_drive_moves_forward_reverse_and_turns_in_place();
void test_simulated_drive_emergency_stop_and_encoders();
void test_simulated_gps_reports_measured_position_separate_from_truth();
void test_simulated_gps_is_reproducible_and_supports_dropouts();
void test_simulated_gps_bias_walk_stays_bounded();
void test_simulated_lidar_ray_casts_obstacles();
void test_simulated_lidar_profile_field_of_view_and_noise();
void test_simulated_lidar_sees_circular_obstacles();
void test_simulation_obstacles_from_graph_edges_line_a_corridor();
void test_simulation_world_helpers_and_state_snapshot();
void test_geo_navigation_phase_names();
void test_heading_estimator_needs_real_movement();
void test_heading_estimator_smoothing_and_course_input();
void test_geo_navigation_route_helpers();
void test_geo_follower_rejects_invalid_routes_and_config();
void test_geo_follower_drives_forward_and_progresses_waypoints();
void test_geo_follower_turns_in_place_for_large_heading_error();
void test_geo_follower_detects_goal_and_stays_finished();
void test_geo_follower_stops_for_obstacles_and_aborts();
void test_geo_follower_single_point_route_is_immediately_reached();
void test_scenario_manual_movement_traces_a_square();
void test_scenario_route_planning_on_shipped_dataset();
void test_scenario_autonomous_run_reaches_destination();
void test_scenario_autonomous_run_survives_gps_noise_and_dropouts();
void test_scenario_autonomous_run_is_reproducible_for_a_seed();
void test_scenario_multiple_routes_over_the_city_park_dataset();
void test_scenario_lidar_equipped_run_sees_corridor_walls();
void test_ui_scene_bounds_cover_every_layer();
void test_ui_scene_svg_draws_every_layer();
void test_ui_scene_svg_handles_empty_and_invalid_input();
void test_ui_scene_svg_honours_style();
void test_scenario_blocked_route_stops_the_robot();
void test_scenario_route_clearance_filter_keeps_the_planned_line_open();
void test_scenario_unreachable_destination_is_reported_not_driven();
void test_maps_nearest_path_index_selects_closest_path();
void test_maps_nearest_path_index_empty_map_returns_invalid_index();
void test_maps_csv_loader_loads_fixture_route_and_sorts_by_sequence();
void test_maps_csv_loader_loads_multiple_paths();
void test_maps_csv_loader_reports_missing_file();
void test_maps_csv_loader_reports_invalid_row();
void test_maps_csv_loader_reports_empty_route();
void test_maps_buchlovice_graph_loader_builds_bidirectional_edges();
void test_maps_buchlovice_graph_loader_reports_invalid_rows();
void test_maps_osm_footway_loader_builds_walkable_graph();
void test_maps_osm_footway_loader_rejects_missing_node_refs();
void test_maps_osm_footway_loader_accepts_inline_single_quote_xml();
void test_maps_osm_footway_loader_rejects_malformed_xml();
void test_maps_osm_footway_loader_rejects_unexpected_closing_tags();
void test_maps_graph_nearest_vertex_and_shortest_path();
void test_maps_graph_sample_route_adds_spacing_points();
void test_maps_route_reuse_decision_uses_distance_from_current_route();
void test_maps_route_corridor_reports_inside_warning_and_violation();
void test_maps_route_corridor_rejects_invalid_inputs();
void test_maps_geofence_contains_points_and_enforces_boundary();
void test_maps_geofence_rejects_invalid_polygons_and_non_finite_points();
void test_maps_geo_helpers_compute_distance_bearing_and_signed_angle();
void test_maps_bearing_to_ahead_point_follows_straight_route();
void test_maps_turn_ahead_detects_left_and_right_turns();
void test_maps_turn_ahead_handles_duplicate_leading_route_points();
void test_maps_turn_ahead_uses_next_measurable_segment_after_duplicate_vertex();
void test_maps_junction_cue_reports_upcoming_left_turn_and_prompt();
void test_maps_junction_cue_reports_no_junction_for_straight_route();
void test_maps_junction_cue_skips_duplicate_vertices_around_turns();
void test_maps_junction_cue_rejects_invalid_inputs();
void test_maps_route_cues_reject_non_finite_coordinates();
void test_maps_turn_ahead_returns_none_for_straight_and_empty_routes();
void test_maps_wrong_direction_detector_uses_persistence_and_distance_growth();
void test_maps_wrong_direction_detector_ignores_stationary_and_noisy_gps();
void test_navigation_go_to_waypoint_stops_inside_tolerance();
void test_navigation_route_follower_advances_waypoints();
void test_navigation_route_follower_finishes_route();
void test_navigation_route_follower_empty_route_reports_finished();
void test_navigation_route_follower_obstacle_does_not_advance_unless_reached();
void test_runtime_countdown_start_and_arrival_flow_is_deterministic();
void test_runtime_faults_on_unhealthy_critical_module();
void test_runtime_obstacle_wait_bypass_and_resume_flow();
void test_runtime_motor_keepalive_due_uses_deterministic_ticks();
void test_mission_target_parser_accepts_geo_and_gps_formats();
void test_mission_target_parser_accepts_labeled_and_hemisphere_formats();
void test_mission_target_parser_rejects_invalid_payloads_with_status();
void test_qr_mission_source_uses_decoder_backend_when_enabled();
void test_runtime_allows_optional_camera_depth_degraded_mode();
void test_runtime_faults_on_stale_module_freshness();
void test_imu_tilt_detects_lateral_acceleration_threshold();
void test_imu_collision_detects_total_acceleration_spike();
void test_imu_pose_fusion_normalizes_heading_and_blends_gps_correction();
void test_imu_pose_fusion_rejects_invalid_weights();
void test_imu_pose_fusion_ignores_gps_without_origin_or_fix();
void test_imu_pose_fusion_weight_boundaries_select_sources();
void test_imu_pose_fusion_replays_fixture_samples();
void test_camera_expected_byte_size_and_shape_for_rgb_frame();
void test_camera_validates_fake_camera_frame_metadata_and_payload();
void test_camera_rejects_invalid_metadata_and_payload_size();
void test_perception_detects_centered_left_and_right_paths();
void test_perception_grass_and_dark_side_coverage_helpers();
void test_perception_low_confidence_invalid_config_and_invalid_frames_fail_safe();
void test_perception_side_coverage_handles_narrow_frames();
void test_perception_dark_obstacle_detects_center_coverage();
void test_perception_diff_obstacle_detects_reference_difference();
void test_perception_hysteresis_triggers_after_streak_and_clears_after_clear_streak();
void test_perception_obstacle_empty_roi_safe_false();
void test_perception_obstacle_threshold_boundary_cases();
void test_perception_obstacle_tracker_resets_state();
void test_perception_obstacle_config_validation_handles_bounds();
void test_perception_detects_people_on_track_from_upright_rgb_blob();
void test_perception_camera_scene_analysis_combines_path_obstacles_and_people();
void test_perception_camera_configs_expose_roi_color_corners_and_obstacle_counts();
void test_perception_libtorch_backend_contract_and_unavailable_fallback();
void test_perception_libtorch_config_validation_rejects_unsafe_model_inputs();
void test_kinect_profile_defaults_have_safe_values();
void test_kinect_profile_validates_rejects_invalid_fields();
void test_kinect_profile_loads_and_parses_config_file();
void test_kinect_profile_load_partial_falls_back_to_defaults();
void test_kinect_profile_load_rejects_missing_file();
void test_kinect_backend_selector_starts_unavailable();
void test_kinect_backend_selector_transitions_through_statuses();
void test_kinect_backend_selector_mark_stale();
void test_normalize_depth_obstacle_summaries_empty_frame_returns_empty();
void test_normalize_depth_obstacle_summaries_detects_left_center_right();
void test_normalize_depth_obstacle_summaries_freshness_timestamp_is_set();
void test_normalize_depth_obstacle_summaries_respects_blob_area_minimum();
void test_obstacle_behavior_clear_to_waiting_when_obstacle_appears();
void test_obstacle_behavior_wait_then_recheck_clears_if_gone();
void test_obstacle_behavior_still_blocked_enters_bypass();
void test_obstacle_behavior_full_bypass_sequence();
void test_obstacle_behavior_select_bypass_direction_from_sensors();
void test_obstacle_behavior_both_sides_blocked_emergency_stop();
void test_obstacle_behavior_max_bypass_attempts_triggers_estop();
void test_obstacle_behavior_obstacle_during_bypass_triggers_estop();
void test_obstacle_behavior_reset_clears_all_state();
void test_obstacle_behavior_bypass_direction_uses_side_coverage_as_tiebreaker();
void test_obstacle_behavior_select_bypass_prefers_clear_lidar_over_depth();
void test_robotour_mission_starts_in_service_phase();
void test_robotour_mission_progresses_through_three_legs();
void test_robotour_mission_target_source_from_qr_payload();
void test_robotour_mission_events_fire_on_transitions();
void test_robotour_mission_aborts_on_emergency();
void test_robotour_mission_arrival_radius_respects_threshold();
void test_robotour_mission_leg_tracking();
void test_operator_input_mock_routes_events();
void test_operator_input_multiple_listeners();
void test_operator_input_inject_all_keys();
void test_beeper_mock_records_beeps();
void test_beeper_mock_silence_until_beeped();
void test_operator_io_headless_text_dashboard_renders_phase();
void test_operator_wizard_requires_ordered_field_confirmations();
void test_operator_wizard_quit_aborts_and_render_sanitizes_controls();
void test_mission_event_logger_stores_events();
void test_mission_event_logger_bypass_events();
void test_mission_tick_logger_captures_all_fields();
void test_mission_tick_logger_csv_header_matches_sample();
void test_c_api_parse_mission_target_valid();
void test_c_api_parse_mission_target_invalid();
void test_c_api_valid_coordinate();
void test_c_api_haversine_distance();
void test_c_api_runtime_safety_field_runner_operator_bridge();
void test_field_preset_buchlovice_has_safe_defaults();
void test_field_preset_no_hardware_demo_is_headless();
void test_field_preset_validate_rejects_invalid();
void test_field_preset_loads_key_value_file();
void test_field_preset_load_rejects_bad_file_values();
void test_field_preset_load_rejects_integer_overflow();
void test_field_preset_load_rejects_non_finite_numbers();
void test_field_preset_load_rejects_malformed_keys_and_booleans();
void test_physical_estop_latch_asserts_and_requires_reset();
void test_runtime_physical_estop_latch_forces_fault();
void test_safety_motor_gate_refuses_motion_until_latch_reset();
void test_field_runner_no_hardware_plan_uses_mocks_and_allows_fixture_run();
void test_field_runner_hardware_plan_requires_physical_estop();
void test_field_runner_hardware_plan_composes_real_backends_when_safe();
void test_robotour_config_exposes_every_layer_as_keys();
void test_robotour_config_round_trips_through_its_own_format();
void test_robotour_config_parses_every_coordinate_spelling();
void test_robotour_config_rejects_malformed_values_and_unknown_keys();
void test_robotour_config_validation_catches_unusable_configurations();
void test_robotour_config_loads_a_preset_file_and_reports_backends();
void test_robotour_config_rejects_a_bad_preset_file();
void test_field_runner_cytron_plan_enforces_bridge_keepalive();
void test_telemetry_parser_loads_robotour_fixture();
void test_telemetry_parser_rejects_bad_schema_and_rows();
void test_telemetry_replay_produces_deterministic_navigation_decisions();
void test_telemetry_converts_buchlovice_tick_and_event_lines();
void test_telemetry_converter_rejects_malformed_and_unsafe_lines();
void test_telemetry_converter_outputs_replay_csv_compatible_ticks();
void test_telemetry_replay_builds_deterministic_ui_snapshot_sequence();
void test_ui_map_view_projects_markers_into_viewport();
void test_ui_map_view_preserves_metric_aspect_ratio_in_wide_viewport();
void test_ui_map_view_marks_off_axis_point_in_degenerate_bounds_invisible();
void test_ui_mission_overlay_classifies_start_operation_current_and_final_positions();
void test_ui_snapshot_composer_connects_map_camera_kinect_and_robot_state();
void test_ui_snapshot_composer_reports_invalid_stream_payloads();
void test_ui_snapshot_composer_reports_invalid_kinect_depth_payloads();
void test_ui_viewport_validation_rejects_excessive_padding_without_overflow();
void test_ui_operator_hud_renders_field_status_cards_and_route_cues();
void test_ui_operator_hud_uses_ansi_in_place_frame_and_fail_closed_statuses();
void test_ui_text_dashboard_renders_mission_stream_and_marker_summary();
void test_ui_renderer_interface_receives_snapshots_at_mission_rate();
void test_ui_renderer_interface_propagates_render_failures_to_event_sink();
#ifdef ROZETA_WITH_SERIAL_MOTORS
void test_serial_motor_formats_normalized_speed_commands();
void test_serial_motor_rejects_invalid_speed_without_writing();
void test_serial_motor_stop_writes_configured_stop_command();
void test_serial_motor_emergency_stop_writes_stop_then_refuses_motion();
void test_serial_motor_clear_emergency_stop_allows_motion();
void test_serial_motor_emergency_stop_writes_stop_even_when_motion_config_is_invalid();
void test_serial_motor_rejects_command_prefix_with_control_characters();
void test_serial_motor_propagates_transport_write_errors();
void test_serial_motor_formats_buchlovice_binary_packets();
void test_serial_motor_buchlovice_stop_and_spin_packets();
void test_serial_motor_buchlovice_emergency_stop_bypasses_invalid_motion_config();
void test_serial_motor_formats_cytron_percent_commands();
void test_serial_motor_cytron_stop_and_estop_write_stop_line();
void test_serial_motor_cytron_rejects_nonpositive_repeat_interval();
#endif
#ifdef ROZETA_WITH_LDROBOT_LIDAR
void test_ldrobot_lidar_parser_parses_ld06_fixture();
void test_ldrobot_lidar_parser_accepts_fragments_and_garbage();
void test_ldrobot_lidar_parser_rejects_bad_crc_and_recovers();
void test_ldrobot_lidar_parser_detects_stream_after_required_valid_frames();
void test_ldrobot_lidar_parser_honors_detection_config_for_public_parse();
void test_ldrobot_lidar_backend_invalid_device_reports_hardware_unavailable();
#endif
#ifdef ROZETA_WITH_YDLIDAR
void test_ydlidar_parser_parses_sample_frame();
void test_ydlidar_parser_accepts_fragmented_frame();
void test_ydlidar_parser_discards_garbage_before_frame();
void test_ydlidar_parser_rejects_invalid_packets_without_throwing();
void test_ydlidar_parser_normalizes_wraparound_angles();
void test_ydlidar_backend_invalid_device_reports_hardware_unavailable();
#endif

void test_health_ages_from_ok_through_stale_to_failed();
void test_health_requires_consecutive_samples_to_recover();
void test_health_invalid_samples_never_look_fresh();
void test_health_unavailable_is_not_a_fault();
void test_health_configured_but_silent_sensor_reports_failed();
void test_health_registry_summarises_worst_critical_sensor();
void test_health_confidence_falls_with_age();
void test_simulated_clock_is_monotonic_and_deterministic();
void test_gps_gate_rejects_structurally_impossible_fixes();
void test_gps_gate_rejects_impossible_jump_without_teleporting();
void test_gps_gate_releases_quarantine_after_repeated_rejects();
void test_gps_gate_detects_frozen_receiver_only_while_moving();
void test_gps_gate_notices_odometry_contradiction();
void test_gps_gate_degrades_confidence_with_accuracy_and_satellites();
void test_gps_gate_reports_jitter_while_stationary();
void test_gps_gate_drives_sensor_health();
void test_gps_gate_config_validation_rejects_nonsense();
void test_safety_machine_runs_only_after_a_passed_preflight();
void test_safety_machine_emergency_stop_latches_and_zeroes_output();
void test_safety_machine_physical_estop_outranks_everything();
void test_safety_machine_degrades_then_recovers_with_hysteresis();
void test_safety_machine_bounds_dead_reckoning_by_time_and_distance();
void test_safety_machine_stops_when_critical_sensor_fails();
void test_safety_governor_never_raises_speed_when_two_faults_combine();
void test_safety_governor_scales_with_pose_confidence();
void test_safety_blind_robot_stops_instead_of_driving();
void test_motor_command_limiter_enforces_the_invariants();
void test_safety_limits_reject_inconsistent_configuration();
void test_safety_history_records_reasons_and_stays_bounded();
void test_fault_schedule_parses_the_scenario_format();
void test_fault_schedule_rejects_typos_instead_of_ignoring_them();
void test_fault_injector_gps_dropout_freeze_and_jump();
void test_fault_injector_lidar_faults_are_visible_but_not_silent();
void test_faulty_drive_reports_io_error_and_asymmetric_failure();
void test_fault_injector_is_reproducible_for_a_given_seed();

void test_pose_fusion_scales_the_gps_weight_by_confidence();
void test_pose_fusion_scales_the_heading_weight_by_confidence();
void test_pose_fusion_default_confidence_preserves_existing_behaviour();

int main(){
    std::vector<std::pair<const char*, std::function<void()>>> tests = {
        {"gps_gga", test_gps_parses_gga_fix},
        {"gps_rmc", test_gps_parses_rmc_course_and_speed},
        {"gps_checksum", test_gps_validates_good_and_bad_checksums},
        {"gps_checksum_malformed", test_gps_rejects_missing_and_malformed_checksums},
        {"gps_detailed_bad_checksum", test_gps_parser_detailed_rejects_invalid_checksum},
        {"gps_detailed_crlf", test_gps_parser_accepts_lowercase_checksum_and_crlf},
        {"gps_stream_fragmented", test_gps_stream_buffers_fragmented_and_multiple_lines},
        {"gps_stream_garbage", test_gps_stream_discards_garbage_before_sentence},
#if !defined(_WIN32)
        {"gps_serial_fragmented", test_gps_serial_receiver_reads_fragmented_fix_from_pty},
        {"gps_serial_skip_bad", test_gps_serial_receiver_skips_bad_checksum_then_returns_good_fix},
        {"gps_serial_timeout", test_gps_serial_receiver_timeout_reports_status},
#endif
        {"gps_serial_invalid_config", test_gps_serial_receiver_rejects_invalid_config},
        {"gps_nmea_sentence_time", test_gps_nmea_carries_the_sentence_time},
        {"gps_nmea_time_fractions", test_gps_nmea_time_handles_fractions_and_absence},
        {"gps_network_invalid_config", test_gps_network_receiver_rejects_invalid_config},
        {"network_gps_payload_parse", test_network_gps_parser_accepts_plain_json_and_nmea_payloads},
        {"network_gps_json_rejects_malformed", test_network_gps_parser_rejects_malformed_json_payloads},
        {"network_gps_udp_packet", test_network_gps_udp_receiver_reads_single_packet_fix},
        {"network_gps_tcp_fragmented", test_network_gps_tcp_receiver_handles_fragmented_newline_feed},
        {"network_gps_timeout_config", test_network_gps_receiver_reports_timeout_and_invalid_config},
        {"network_gps_tcp_open_timeout", test_network_gps_tcp_open_uses_configured_finite_timeout},
        {"network_gps_tcp_read_deadline", test_network_gps_tcp_read_has_overall_deadline_without_newline},
        {"network_gps_tcp_partial_deadline", test_network_gps_tcp_read_uses_remaining_deadline_after_partial_payload},
        {"odometry", test_odometry_differential_drive_forward_and_turn},
        {"odometry_ccw_heading", test_odometry_heading_counterclockwise_positive},
        {"odometry_seed_ticks", test_odometry_seed_ticks_prevents_startup_jump},
        {"coordinates", test_coordinate_local_conversion},
        {"obstacles", test_obstacle_sector_calculation},
        {"depth_obstacles", test_depth_frame_extracts_nearest_obstacle_sectors},
        {"depth_point_cloud", test_depth_frame_to_point_cloud_projects_valid_pixels},
        {"depth_edge_cases", test_depth_frame_ignores_invalid_pixels_and_bad_fixtures},
        {"motors", test_motor_command_validation_and_estop},
        {"motors_non_finite", test_motor_rejects_non_finite_speeds},
        {"speed_ramp_accelerate", test_speed_ramp_accelerates_linearly_to_target},
        {"speed_ramp_decelerate", test_speed_ramp_decelerates_to_zero_and_stops},
        {"speed_ramp_invalid", test_speed_ramp_rejects_invalid_configuration},
        {"smooth_drive_accelerate_brake", test_smooth_drive_accelerates_and_brakes_within_profile},
        {"smooth_drive_keepalive", test_smooth_drive_repeats_command_for_bridge_watchdog},
        {"smooth_drive_reverse", test_smooth_drive_reverses_through_standstill_and_validates},
        {"smooth_drive_estop", test_smooth_drive_emergency_stop_bypasses_ramp},
        {"config", test_config_loader_reads_key_values},
        {"config_load_file_status", test_config_load_file_reports_missing_and_loads_existing},
        {"normalize_angle", test_normalize_angle_wraps_small_and_huge_magnitudes},
        {"logging_global_swap", test_logging_global_logger_swap_and_null_safe},
        {"logging_csv_escaping", test_logging_csv_file_logger_escapes_quotes_commas_newlines},
        {"logging_csv_unopenable", test_logging_csv_file_logger_reports_unopenable_path},
        {"serial_port", test_serial_port_open_timeout_write_read_and_close},
        {"serial_invalid_config", test_serial_port_rejects_invalid_configuration},
        {"motor_calibration_round_trip", test_motor_calibration_save_load_round_trip},
        {"motor_calibration_invalid", test_motor_calibration_load_rejects_invalid_values},
        {"motor_calibration_missing", test_motor_calibration_load_missing_file_returns_error},
        {"calibration_round_trip", test_calibration_save_load_round_trip_for_field_tools},
        {"calibration_invalid", test_calibration_rejects_non_finite_and_out_of_range_values},
        {"calibration_bad_files", test_calibration_load_fails_closed_for_bad_files},
        {"calibration_required_keys", test_calibration_load_requires_complete_unique_snapshot_keys},
        {"calibration_revision_chars", test_calibration_rejects_revision_values_that_break_key_value_files},
        {"calibration_checklist", test_calibration_checklist_reports_camera_motor_gps_and_threshold_steps},
        {"hardware_smoke_matrix", test_hardware_smoke_matrix_builds_lifted_wheel_and_sensor_checks},
        {"hardware_smoke_fail_closed", test_hardware_smoke_matrix_fails_closed_without_estop_or_wheel_lift},
        {"hardware_smoke_render", test_hardware_smoke_matrix_renders_deterministic_operator_plan},
        {"hardware_smoke_enabled_sources", test_hardware_smoke_matrix_validates_only_enabled_source_groups},
        {"hardware_smoke_quote", test_hardware_smoke_matrix_rejects_invalid_calibration_and_quotes_commands},
        {"geometry_project_segment", test_geometry_projects_point_on_segment},
        {"geometry_degenerate_segment", test_geometry_degenerate_segment_projects_to_start},
        {"geometry_polyline", test_geometry_polyline_distance_and_length},
        {"geometry_point_in_polygon", test_geometry_point_in_polygon},
        {"geometry_bounds", test_geometry_bounds},
        {"geometry_ray_segment", test_geometry_ray_hits_and_misses_segment},
        {"geometry_cast_ray", test_geometry_cast_ray_returns_closest_hit},
        {"geometry_ray_circle", test_geometry_ray_circle_intersection},
        {"geometry_non_finite", test_geometry_rejects_non_finite_input},
        {"geodesy_haversine", test_geodesy_haversine_matches_known_distances},
        {"geodesy_local_round_trip", test_geodesy_local_round_trip},
        {"geodesy_bearing_heading", test_geodesy_bearing_and_heading_conversions},
        {"geodesy_valid_coordinate", test_geodesy_validates_coordinates},
        {"geodesy_resample", test_geodesy_resamples_polyline_with_exact_endpoints},
        {"geodesy_bounds", test_geodesy_bounds_and_interpolation},
        {"geodesy_meters_per_degree", test_geodesy_meters_per_degree_shrinks_towards_poles},
        {"kinematics_config", test_kinematics_validates_chassis_config},
        {"kinematics_tank_mix", test_kinematics_tank_mix_counter_rotates_through_turns},
        {"kinematics_arcade_mix", test_kinematics_arcade_mix_arcs_and_respects_limit},
        {"kinematics_mix_clamp", test_kinematics_mix_clamps_invalid_input},
        {"kinematics_twist", test_kinematics_wheel_speeds_and_twist_round_trip},
        {"kinematics_integrate", test_kinematics_integrates_straight_turn_and_spin},
        {"kinematics_motor_command", test_kinematics_turning_in_place_detection_and_motor_commands},
        {"map_graph_snap_segment", test_map_graph_snaps_onto_segment_not_only_vertices},
        {"map_graph_snap_rejects", test_map_graph_snap_rejects_far_and_invalid_points},
        {"map_graph_index", test_map_graph_index_matches_brute_force_snap},
        {"map_graph_index_far", test_map_graph_index_rejects_far_away_points_quickly},
        {"map_graph_validate", test_map_graph_validate_reports_components_and_length},
        {"map_graph_astar", test_map_graph_astar_matches_dijkstra},
        {"map_graph_astar_invalid", test_map_graph_astar_rejects_invalid_and_unreachable_vertices},
        {"map_graph_plan_route", test_map_graph_plan_route_snaps_both_endpoints},
        {"map_graph_plan_same_edge", test_map_graph_plan_route_on_one_edge_stays_on_it},
        {"map_graph_plan_invalid", test_map_graph_plan_route_reports_unreachable_and_invalid_input},
        {"map_graph_shipped_dataset", test_map_graph_loads_shipped_openstreetmap_dataset},
        {"map_catalog_shipped", test_map_catalog_loads_shipped_catalog},
        {"map_catalog_bad_input", test_map_catalog_reports_bad_input},
        {"simulation_noise_determinism", test_simulation_noise_is_deterministic_for_a_seed},
        {"simulation_world_validate", test_simulation_world_validates_config},
        {"simulated_drive_motion", test_simulated_drive_moves_forward_reverse_and_turns_in_place},
        {"simulated_drive_estop", test_simulated_drive_emergency_stop_and_encoders},
        {"simulated_gps_measured", test_simulated_gps_reports_measured_position_separate_from_truth},
        {"simulated_gps_repeatable", test_simulated_gps_is_reproducible_and_supports_dropouts},
        {"simulated_gps_bias", test_simulated_gps_bias_walk_stays_bounded},
        {"simulated_lidar_raycast", test_simulated_lidar_ray_casts_obstacles},
        {"simulated_lidar_profile", test_simulated_lidar_profile_field_of_view_and_noise},
        {"simulated_lidar_circles", test_simulated_lidar_sees_circular_obstacles},
        {"simulation_graph_obstacles", test_simulation_obstacles_from_graph_edges_line_a_corridor},
        {"simulation_world_state", test_simulation_world_helpers_and_state_snapshot},
        {"geo_navigation_phases", test_geo_navigation_phase_names},
        {"heading_estimator_movement", test_heading_estimator_needs_real_movement},
        {"heading_estimator_smoothing", test_heading_estimator_smoothing_and_course_input},
        {"geo_navigation_helpers", test_geo_navigation_route_helpers},
        {"geo_follower_invalid", test_geo_follower_rejects_invalid_routes_and_config},
        {"geo_follower_waypoints", test_geo_follower_drives_forward_and_progresses_waypoints},
        {"geo_follower_turn_in_place", test_geo_follower_turns_in_place_for_large_heading_error},
        {"geo_follower_goal", test_geo_follower_detects_goal_and_stays_finished},
        {"geo_follower_obstacle_abort", test_geo_follower_stops_for_obstacles_and_aborts},
        {"geo_follower_single_point", test_geo_follower_single_point_route_is_immediately_reached},
        {"scenario_manual_square", test_scenario_manual_movement_traces_a_square},
        {"scenario_route_planning", test_scenario_route_planning_on_shipped_dataset},
        {"scenario_autonomous_run", test_scenario_autonomous_run_reaches_destination},
        {"scenario_noisy_run", test_scenario_autonomous_run_survives_gps_noise_and_dropouts},
        {"scenario_reproducible_run", test_scenario_autonomous_run_is_reproducible_for_a_seed},
        {"scenario_multiple_routes", test_scenario_multiple_routes_over_the_city_park_dataset},
        {"scenario_lidar_run", test_scenario_lidar_equipped_run_sees_corridor_walls},
        {"ui_scene_bounds", test_ui_scene_bounds_cover_every_layer},
        {"ui_scene_svg_layers", test_ui_scene_svg_draws_every_layer},
        {"ui_scene_svg_invalid", test_ui_scene_svg_handles_empty_and_invalid_input},
        {"ui_scene_svg_style", test_ui_scene_svg_honours_style},
        {"scenario_blocked_route", test_scenario_blocked_route_stops_the_robot},
        {"scenario_route_clearance", test_scenario_route_clearance_filter_keeps_the_planned_line_open},
        {"scenario_unreachable", test_scenario_unreachable_destination_is_reported_not_driven},
        {"maps_nearest_path", test_maps_nearest_path_index_selects_closest_path},
        {"maps_empty_index", test_maps_nearest_path_index_empty_map_returns_invalid_index},
        {"maps_csv_fixture", test_maps_csv_loader_loads_fixture_route_and_sorts_by_sequence},
        {"maps_csv_multiple_paths", test_maps_csv_loader_loads_multiple_paths},
        {"maps_missing_file", test_maps_csv_loader_reports_missing_file},
        {"maps_invalid_row", test_maps_csv_loader_reports_invalid_row},
        {"maps_empty_route", test_maps_csv_loader_reports_empty_route},
        {"maps_buchlovice_graph", test_maps_buchlovice_graph_loader_builds_bidirectional_edges},
        {"maps_buchlovice_graph_invalid", test_maps_buchlovice_graph_loader_reports_invalid_rows},
        {"maps_osm_footways", test_maps_osm_footway_loader_builds_walkable_graph},
        {"maps_osm_footways_invalid", test_maps_osm_footway_loader_rejects_missing_node_refs},
        {"maps_osm_footways_inline", test_maps_osm_footway_loader_accepts_inline_single_quote_xml},
        {"maps_osm_footways_malformed", test_maps_osm_footway_loader_rejects_malformed_xml},
        {"maps_osm_footways_bad_close", test_maps_osm_footway_loader_rejects_unexpected_closing_tags},
        {"maps_graph_shortest_path", test_maps_graph_nearest_vertex_and_shortest_path},
        {"maps_graph_sample_route", test_maps_graph_sample_route_adds_spacing_points},
        {"maps_graph_route_reuse", test_maps_route_reuse_decision_uses_distance_from_current_route},
        {"maps_route_corridor", test_maps_route_corridor_reports_inside_warning_and_violation},
        {"maps_route_corridor_invalid", test_maps_route_corridor_rejects_invalid_inputs},
        {"maps_geofence", test_maps_geofence_contains_points_and_enforces_boundary},
        {"maps_geofence_invalid", test_maps_geofence_rejects_invalid_polygons_and_non_finite_points},
        {"maps_geo_helpers", test_maps_geo_helpers_compute_distance_bearing_and_signed_angle},
        {"maps_bearing_ahead", test_maps_bearing_to_ahead_point_follows_straight_route},
        {"maps_turn_ahead", test_maps_turn_ahead_detects_left_and_right_turns},
        {"maps_turn_duplicate_points", test_maps_turn_ahead_handles_duplicate_leading_route_points},
        {"maps_turn_duplicate_vertex", test_maps_turn_ahead_uses_next_measurable_segment_after_duplicate_vertex},
        {"maps_junction_cue", test_maps_junction_cue_reports_upcoming_left_turn_and_prompt},
        {"maps_junction_cue_straight", test_maps_junction_cue_reports_no_junction_for_straight_route},
        {"maps_junction_cue_duplicates", test_maps_junction_cue_skips_duplicate_vertices_around_turns},
        {"maps_junction_cue_invalid", test_maps_junction_cue_rejects_invalid_inputs},
        {"maps_route_cue_invalid", test_maps_route_cues_reject_non_finite_coordinates},
        {"maps_turn_ahead_none", test_maps_turn_ahead_returns_none_for_straight_and_empty_routes},
        {"maps_wrong_direction", test_maps_wrong_direction_detector_uses_persistence_and_distance_growth},
        {"maps_wrong_direction_noise", test_maps_wrong_direction_detector_ignores_stationary_and_noisy_gps},
        {"navigation_waypoint_tolerance", test_navigation_go_to_waypoint_stops_inside_tolerance},
        {"navigation_route_advance", test_navigation_route_follower_advances_waypoints},
        {"navigation_route_complete", test_navigation_route_follower_finishes_route},
        {"navigation_route_empty", test_navigation_route_follower_empty_route_reports_finished},
        {"navigation_route_obstacle", test_navigation_route_follower_obstacle_does_not_advance_unless_reached},
        {"runtime_countdown_arrival", test_runtime_countdown_start_and_arrival_flow_is_deterministic},
        {"runtime_fault_unhealthy_module", test_runtime_faults_on_unhealthy_critical_module},
        {"runtime_obstacle_bypass", test_runtime_obstacle_wait_bypass_and_resume_flow},
        {"runtime_motor_keepalive", test_runtime_motor_keepalive_due_uses_deterministic_ticks},
        {"mission_geo_gps_parse", test_mission_target_parser_accepts_geo_and_gps_formats},
        {"mission_labeled_hemisphere_parse", test_mission_target_parser_accepts_labeled_and_hemisphere_formats},
        {"mission_rejects_invalid_payloads", test_mission_target_parser_rejects_invalid_payloads_with_status},
        {"mission_qr_backend", test_qr_mission_source_uses_decoder_backend_when_enabled},
        {"runtime_optional_degraded", test_runtime_allows_optional_camera_depth_degraded_mode},
        {"runtime_stale_module", test_runtime_faults_on_stale_module_freshness},
        {"imu_tilt", test_imu_tilt_detects_lateral_acceleration_threshold},
        {"imu_collision", test_imu_collision_detects_total_acceleration_spike},
        {"imu_pose_fusion", test_imu_pose_fusion_normalizes_heading_and_blends_gps_correction},
        {"imu_invalid_weights", test_imu_pose_fusion_rejects_invalid_weights},
        {"imu_gps_edge_cases", test_imu_pose_fusion_ignores_gps_without_origin_or_fix},
        {"imu_weight_boundaries", test_imu_pose_fusion_weight_boundaries_select_sources},
        {"imu_fixture_replay", test_imu_pose_fusion_replays_fixture_samples},
        {"camera_shape", test_camera_expected_byte_size_and_shape_for_rgb_frame},
        {"camera_fake_frame", test_camera_validates_fake_camera_frame_metadata_and_payload},
        {"camera_invalid_frame", test_camera_rejects_invalid_metadata_and_payload_size},
        {"perception_path", test_perception_detects_centered_left_and_right_paths},
        {"perception_coverage", test_perception_grass_and_dark_side_coverage_helpers},
        {"perception_invalid", test_perception_low_confidence_invalid_config_and_invalid_frames_fail_safe},
        {"perception_narrow", test_perception_side_coverage_handles_narrow_frames},
        {"perception_dark_obstacle", test_perception_dark_obstacle_detects_center_coverage},
        {"perception_diff_obstacle", test_perception_diff_obstacle_detects_reference_difference},
        {"perception_hysteresis", test_perception_hysteresis_triggers_after_streak_and_clears_after_clear_streak},
        {"perception_empty_roi", test_perception_obstacle_empty_roi_safe_false},
        {"perception_threshold", test_perception_obstacle_threshold_boundary_cases},
        {"perception_tracker_reset", test_perception_obstacle_tracker_resets_state},
        {"perception_config_validation", test_perception_obstacle_config_validation_handles_bounds},
        {"perception_people_on_track", test_perception_detects_people_on_track_from_upright_rgb_blob},
        {"perception_camera_scene", test_perception_camera_scene_analysis_combines_path_obstacles_and_people},
        {
            "perception_camera_settings",
            test_perception_camera_configs_expose_roi_color_corners_and_obstacle_counts,
        },
        {
            "perception_libtorch_contract",
            test_perception_libtorch_backend_contract_and_unavailable_fallback,
        },
        {
            "perception_libtorch_config",
            test_perception_libtorch_config_validation_rejects_unsafe_model_inputs,
        },
        {"kinect_profile_defaults", test_kinect_profile_defaults_have_safe_values},
        {"kinect_profile_validate", test_kinect_profile_validates_rejects_invalid_fields},
        {"kinect_profile_load", test_kinect_profile_loads_and_parses_config_file},
        {"kinect_profile_partial", test_kinect_profile_load_partial_falls_back_to_defaults},
        {"kinect_profile_missing", test_kinect_profile_load_rejects_missing_file},
        {"kinect_backend_unavailable", test_kinect_backend_selector_starts_unavailable},
        {"kinect_backend_transitions", test_kinect_backend_selector_transitions_through_statuses},
        {"kinect_backend_stale", test_kinect_backend_selector_mark_stale},
        {"kinect_summaries_empty", test_normalize_depth_obstacle_summaries_empty_frame_returns_empty},
        {"kinect_summaries_sectors", test_normalize_depth_obstacle_summaries_detects_left_center_right},
        {"kinect_summaries_freshness", test_normalize_depth_obstacle_summaries_freshness_timestamp_is_set},
        {"kinect_summaries_blob", test_normalize_depth_obstacle_summaries_respects_blob_area_minimum},
        {"obeh_clear_to_wait", test_obstacle_behavior_clear_to_waiting_when_obstacle_appears},
        {"obeh_wait_recheck", test_obstacle_behavior_wait_then_recheck_clears_if_gone},
        {"obeh_blocked_bypass", test_obstacle_behavior_still_blocked_enters_bypass},
        {"obeh_full_bypass", test_obstacle_behavior_full_bypass_sequence},
        {"obeh_bypass_dir", test_obstacle_behavior_select_bypass_direction_from_sensors},
        {"obeh_both_blocked", test_obstacle_behavior_both_sides_blocked_emergency_stop},
        {"obeh_max_attempts", test_obstacle_behavior_max_bypass_attempts_triggers_estop},
        {"obeh_bypass_estop", test_obstacle_behavior_obstacle_during_bypass_triggers_estop},
        {"obeh_reset", test_obstacle_behavior_reset_clears_all_state},
        {"obeh_coverage_tie", test_obstacle_behavior_bypass_direction_uses_side_coverage_as_tiebreaker},
        {"obeh_lidar_prefer", test_obstacle_behavior_select_bypass_prefers_clear_lidar_over_depth},
        {"rmis_start", test_robotour_mission_starts_in_service_phase},
        {"rmis_three_legs", test_robotour_mission_progresses_through_three_legs},
        {"rmis_qr_target", test_robotour_mission_target_source_from_qr_payload},
        {"rmis_events", test_robotour_mission_events_fire_on_transitions},
        {"rmis_abort", test_robotour_mission_aborts_on_emergency},
        {"rmis_arrival", test_robotour_mission_arrival_radius_respects_threshold},
        {"rmis_legs", test_robotour_mission_leg_tracking},
        {"opio_mock_keys", test_operator_input_mock_routes_events},
        {"opio_multi_listen", test_operator_input_multiple_listeners},
        {"opio_all_keys", test_operator_input_inject_all_keys},
        {"opio_beeper", test_beeper_mock_records_beeps},
        {"opio_beeper_silent", test_beeper_mock_silence_until_beeped},
        {"opio_dashboard", test_operator_io_headless_text_dashboard_renders_phase},
        {"opio_field_wizard", test_operator_wizard_requires_ordered_field_confirmations},
        {"opio_field_wizard_abort", test_operator_wizard_quit_aborts_and_render_sanitizes_controls},
        {"telm_events", test_mission_event_logger_stores_events},
        {"telm_bypass", test_mission_event_logger_bypass_events},
        {"telm_tick_csv", test_mission_tick_logger_captures_all_fields},
        {"telm_tick_header", test_mission_tick_logger_csv_header_matches_sample},
        {"capi_mission", test_c_api_parse_mission_target_valid},
        {"capi_mission_inv", test_c_api_parse_mission_target_invalid},
        {"capi_coord", test_c_api_valid_coordinate},
        {"capi_haversine", test_c_api_haversine_distance},
        {"capi_runtime_safety_field_operator", test_c_api_runtime_safety_field_runner_operator_bridge},
        {"field_preset_buchlovice", test_field_preset_buchlovice_has_safe_defaults},
        {"field_preset_demo", test_field_preset_no_hardware_demo_is_headless},
        {"field_preset_invalid", test_field_preset_validate_rejects_invalid},
        {"field_preset_load_file", test_field_preset_loads_key_value_file},
        {"field_preset_load_bad", test_field_preset_load_rejects_bad_file_values},
        {"field_preset_load_overflow", test_field_preset_load_rejects_integer_overflow},
        {"field_preset_load_non_finite", test_field_preset_load_rejects_non_finite_numbers},
        {"field_preset_load_malformed", test_field_preset_load_rejects_malformed_keys_and_booleans},
        {"safety_estop_latch", test_physical_estop_latch_asserts_and_requires_reset},
        {"safety_runtime_estop", test_runtime_physical_estop_latch_forces_fault},
        {"safety_motor_gate", test_safety_motor_gate_refuses_motion_until_latch_reset},
        {"field_runner_no_hardware", test_field_runner_no_hardware_plan_uses_mocks_and_allows_fixture_run},
        {"field_runner_requires_estop", test_field_runner_hardware_plan_requires_physical_estop},
        {"field_runner_hardware_plan", test_field_runner_hardware_plan_composes_real_backends_when_safe},
        {"robotour_config_keys", test_robotour_config_exposes_every_layer_as_keys},
        {"robotour_config_round_trip", test_robotour_config_round_trips_through_its_own_format},
        {"robotour_config_coordinates", test_robotour_config_parses_every_coordinate_spelling},
        {"robotour_config_bad_values", test_robotour_config_rejects_malformed_values_and_unknown_keys},
        {"robotour_config_validation", test_robotour_config_validation_catches_unusable_configurations},
        {"robotour_config_file", test_robotour_config_loads_a_preset_file_and_reports_backends},
        {"robotour_config_bad_file", test_robotour_config_rejects_a_bad_preset_file},
        {"field_runner_cytron_keepalive", test_field_runner_cytron_plan_enforces_bridge_keepalive},
        {"telemetry_parser_fixture", test_telemetry_parser_loads_robotour_fixture},
        {"telemetry_parser_errors", test_telemetry_parser_rejects_bad_schema_and_rows},
        {"telemetry_replay_deterministic", test_telemetry_replay_produces_deterministic_navigation_decisions},
        {"telemetry_buchlovice_convert", test_telemetry_converts_buchlovice_tick_and_event_lines},
        {"telemetry_buchlovice_invalid", test_telemetry_converter_rejects_malformed_and_unsafe_lines},
        {"telemetry_buchlovice_csv", test_telemetry_converter_outputs_replay_csv_compatible_ticks},
        {"telemetry_ui_snapshots", test_telemetry_replay_builds_deterministic_ui_snapshot_sequence},
        {"ui_map_projection", test_ui_map_view_projects_markers_into_viewport},
        {"ui_metric_aspect", test_ui_map_view_preserves_metric_aspect_ratio_in_wide_viewport},
        {"ui_degenerate_bounds", test_ui_map_view_marks_off_axis_point_in_degenerate_bounds_invisible},
        {"ui_mission_overlay", test_ui_mission_overlay_classifies_start_operation_current_and_final_positions},
        {"ui_snapshot_composer", test_ui_snapshot_composer_connects_map_camera_kinect_and_robot_state},
        {"ui_invalid_stream", test_ui_snapshot_composer_reports_invalid_stream_payloads},
        {"ui_invalid_depth", test_ui_snapshot_composer_reports_invalid_kinect_depth_payloads},
        {"ui_invalid_viewport", test_ui_viewport_validation_rejects_excessive_padding_without_overflow},
        {"ui_operator_hud", test_ui_operator_hud_renders_field_status_cards_and_route_cues},
        {"ui_operator_hud_fail_closed", test_ui_operator_hud_uses_ansi_in_place_frame_and_fail_closed_statuses},
        {"ui_text_dashboard", test_ui_text_dashboard_renders_mission_stream_and_marker_summary},
        {"ui_renderer_frames", test_ui_renderer_interface_receives_snapshots_at_mission_rate},
        {"ui_renderer_status", test_ui_renderer_interface_propagates_render_failures_to_event_sink},
        {"imu_fusion_confidence_gps", test_pose_fusion_scales_the_gps_weight_by_confidence},
        {"imu_fusion_confidence_heading", test_pose_fusion_scales_the_heading_weight_by_confidence},
        {"imu_fusion_default_confidence", test_pose_fusion_default_confidence_preserves_existing_behaviour},
        {"health_ageing", test_health_ages_from_ok_through_stale_to_failed},
        {"health_hysteresis", test_health_requires_consecutive_samples_to_recover},
        {"health_invalid_not_fresh", test_health_invalid_samples_never_look_fresh},
        {"health_unavailable", test_health_unavailable_is_not_a_fault},
        {"health_silent_sensor", test_health_configured_but_silent_sensor_reports_failed},
        {"health_registry_summary", test_health_registry_summarises_worst_critical_sensor},
        {"health_confidence", test_health_confidence_falls_with_age},
        {"clock_simulated", test_simulated_clock_is_monotonic_and_deterministic},
        {"gps_gate_structural", test_gps_gate_rejects_structurally_impossible_fixes},
        {"gps_gate_jump", test_gps_gate_rejects_impossible_jump_without_teleporting},
        {"gps_gate_quarantine", test_gps_gate_releases_quarantine_after_repeated_rejects},
        {"gps_gate_frozen", test_gps_gate_detects_frozen_receiver_only_while_moving},
        {"gps_gate_odometry", test_gps_gate_notices_odometry_contradiction},
        {"gps_gate_accuracy", test_gps_gate_degrades_confidence_with_accuracy_and_satellites},
        {"gps_gate_jitter", test_gps_gate_reports_jitter_while_stationary},
        {"gps_gate_health", test_gps_gate_drives_sensor_health},
        {"gps_gate_config", test_gps_gate_config_validation_rejects_nonsense},
        {"safety_preflight", test_safety_machine_runs_only_after_a_passed_preflight},
        {"safety_estop_latch", test_safety_machine_emergency_stop_latches_and_zeroes_output},
        {"safety_physical_estop", test_safety_machine_physical_estop_outranks_everything},
        {"safety_degraded_recovery", test_safety_machine_degrades_then_recovers_with_hysteresis},
        {"safety_bounded_autonomy", test_safety_machine_bounds_dead_reckoning_by_time_and_distance},
        {"safety_critical_failure", test_safety_machine_stops_when_critical_sensor_fails},
        {"safety_governor_combines", test_safety_governor_never_raises_speed_when_two_faults_combine},
        {"safety_governor_confidence", test_safety_governor_scales_with_pose_confidence},
        {"safety_blind_stops", test_safety_blind_robot_stops_instead_of_driving},
        {"safety_motor_limiter", test_motor_command_limiter_enforces_the_invariants},
        {"safety_config_validation", test_safety_limits_reject_inconsistent_configuration},
        {"safety_history", test_safety_history_records_reasons_and_stays_bounded},
        {"faults_parse", test_fault_schedule_parses_the_scenario_format},
        {"faults_parse_errors", test_fault_schedule_rejects_typos_instead_of_ignoring_them},
        {"faults_gps", test_fault_injector_gps_dropout_freeze_and_jump},
        {"faults_lidar", test_fault_injector_lidar_faults_are_visible_but_not_silent},
        {"faults_drive", test_faulty_drive_reports_io_error_and_asymmetric_failure},
        {"faults_reproducible", test_fault_injector_is_reproducible_for_a_given_seed},
#ifdef ROZETA_WITH_SERIAL_MOTORS
        {"serial_motor_format", test_serial_motor_formats_normalized_speed_commands},
        {"serial_motor_invalid_speed", test_serial_motor_rejects_invalid_speed_without_writing},
        {"serial_motor_stop", test_serial_motor_stop_writes_configured_stop_command},
        {"serial_motor_estop", test_serial_motor_emergency_stop_writes_stop_then_refuses_motion},
        {"serial_motor_clear_estop", test_serial_motor_clear_emergency_stop_allows_motion},
        {
            "serial_motor_estop_ignores_motion_config",
            test_serial_motor_emergency_stop_writes_stop_even_when_motion_config_is_invalid,
        },
        {"serial_motor_prefix_validation", test_serial_motor_rejects_command_prefix_with_control_characters},
        {"serial_motor_write_error", test_serial_motor_propagates_transport_write_errors},
        {"serial_motor_buchlovice_packet", test_serial_motor_formats_buchlovice_binary_packets},
        {"serial_motor_buchlovice_stop_spin", test_serial_motor_buchlovice_stop_and_spin_packets},
        {"serial_motor_buchlovice_estop", test_serial_motor_buchlovice_emergency_stop_bypasses_invalid_motion_config},
        {"serial_motor_cytron_format", test_serial_motor_formats_cytron_percent_commands},
        {"serial_motor_cytron_stop_estop", test_serial_motor_cytron_stop_and_estop_write_stop_line},
        {"serial_motor_cytron_repeat_interval", test_serial_motor_cytron_rejects_nonpositive_repeat_interval},
#endif
#ifdef ROZETA_WITH_LDROBOT_LIDAR
        {"ldrobot_lidar_fixture", test_ldrobot_lidar_parser_parses_ld06_fixture},
        {"ldrobot_lidar_fragments", test_ldrobot_lidar_parser_accepts_fragments_and_garbage},
        {"ldrobot_lidar_bad_crc", test_ldrobot_lidar_parser_rejects_bad_crc_and_recovers},
        {"ldrobot_lidar_detect", test_ldrobot_lidar_parser_detects_stream_after_required_valid_frames},
        {"ldrobot_lidar_config", test_ldrobot_lidar_parser_honors_detection_config_for_public_parse},
        {"ldrobot_lidar_invalid_device", test_ldrobot_lidar_backend_invalid_device_reports_hardware_unavailable},
#endif
#ifdef ROZETA_WITH_YDLIDAR
        {"ydlidar_parse_fixture", test_ydlidar_parser_parses_sample_frame},
        {"ydlidar_fragmented", test_ydlidar_parser_accepts_fragmented_frame},
        {"ydlidar_garbage", test_ydlidar_parser_discards_garbage_before_frame},
        {"ydlidar_invalid_safe", test_ydlidar_parser_rejects_invalid_packets_without_throwing},
        {"ydlidar_wraparound", test_ydlidar_parser_normalizes_wraparound_angles},
        {"ydlidar_invalid_device", test_ydlidar_backend_invalid_device_reports_hardware_unavailable},
#endif
    };
    int failed = 0;
    for (auto &test : tests) {
        try { test.second(); std::cout << "[PASS] " << test.first << "\n"; }
        catch (const std::exception &e) { ++failed; std::cerr << "[FAIL] " << test.first << ": " << e.what() << "\n"; }
    }
    return failed == 0 ? 0 : 1;
}
